### ISSUE TITLE
Could Not resolve com.gitlab.adgate-media:androidsdk:2.1.1

### ISSUE THREAD

**Issue by jpreiditsch** [adgatemedia/adgate-rewards-android-sdk#3]
As of Tuesday May 14, 4PM EDT the gitlab repository for adgate on jitpack.io appears to now be password protected. 
This prevents the download of the dependencies from agate

`Execution failed for task ':fongoPhone:checkAndroidDebugDuplicateClasses'.
> Could not resolve all files for configuration ':fongoPhone:androidDebugRuntimeClasspath'.
   > Could not resolve com.gitlab.adgate-media:androidsdk:2.1.1.
     Required by:
         project :fongoPhone
      > Could not resolve com.gitlab.adgate-media:androidsdk:2.1.1.
         > Could not get resource 'https://jitpack.io/com/gitlab/adgate-media/androidsdk/2.1.1/androidsdk-2.1.1.pom'.
            > Could not GET 'https://jitpack.io/com/gitlab/adgate-media/androidsdk/2.1.1/androidsdk-2.1.1.pom'. Received status code 401 from server: Unauthorized
`

**Comment by eblanshey** [comment]
@jpreiditsch sorry for the issue. Can you please try again now? The issue should be fixed.

**Comment by jpreiditsch** [comment]
@eblanshey 
We are still seeing the 401 error when gradle is trying to load the maven meta data from jitpack.io. Visiting the link via browser requests a user name and password 'https://jitpack.io/com/gitlab/adgate-media/androidsdk/2.1.1/androidsdk-2.1.1.pom'

**Comment by eblanshey** [comment]
@jpreiditsch the link works for me in incognito. Perhaps it just took some time. Are you still getting the issue?

**Comment by jpreiditsch** [comment]
@eblanshey it appears to be resolved now! Thank you!!

**Comment by eblanshey** [comment]
Great! Sorry for the delays!
